### ISSUE TITLE
H8. Como familiar, eu quero poder adicionar datas importantes às lembranças, para que todos os amigos e familiares possam celebrar os momentos especiais vividos com ele.

### ISSUE THREAD

**Issue by vitoroli22** [kenuysaa/app-homenagens-postumas#11]
# Critérios de aceitação
- O usuário define a data de evento disponível na publicação das lembranças, esta opção estará em formato de calendário.
- As datas definidas pelo usuário devem ser visíveis a todos que têm acesso ao memorial.
- Permitir que o usuário escolha se deseja receber notificações de proximidade da data do evento. As opções de notificações de proximidade da data devem incluir: 1 semana antes, 3 dias antes e 9h no dia do evento.
- O usuário poderá desativar as notificações de proximidade a qualquer momento nas opções disponíveis na publicação.

# Regras de negócios
- Inclui medidas para garantir a preservação a longo prazo das memórias e histórias compartilhadas, protegendo-as contra perda.

**Comment by vitoroli22** [comment]
- [x] Mudanças a serem feitas no critério 1: Adicionar onde estará disponível para o usuário definir a data de evento.

**Comment by SebastianXavier333** [comment]
- [x] Mudanças a serem feitas no C5: Notificações, apareceram no e-mail ou terá no próprio sistema, para notificar o usuário.
