### ISSUE TITLE
H8. Como familiar, eu quero uma area para organizar publicações em sessão e destaca-las, para que eu possa juntar publicações da vida do falecido.

### ISSUE THREAD

**Issue by vitoroli22** [kenuysaa/app-homenagens-postumas#12]
# Critério de aceitação
- As publicações serão organizadas em areas chamadas "Sessões de memorias". Ela estará disponivel na barra de navegação da pagina do memorial.
- As sessões poderá ser adicionada por qualquer usuario que faça publicação no memorial.
 - As sessões poderão ser arquivadas pelos responsaveis do memorial, sendo sujeitas a exclusão automatica após 90 dias ou manualmente pelo responsavel.
 - As sessões serão definidas por "Nome da Sessão", "Periodo do momento", "Descrição" e "Adicionar publicações".
 - Uma sessão poderá ser criada a partir de publicações de um perfil de usuario que ja faleceu.
 - Sessões podem ser criadas em perfis de usuarios que estejam nos seus ultimos momentos de vida, essas sessões não poderão ser editadas por qualquer usuario apos o perfil do morto ser transformado em um memorial.

**Comment by vitoroli22** [comment]
- [x] excluir história, substituir para sessão para visualizar somente mídia de foto e vídeo.

**Comment by SebastianXavier333** [comment]
- [x] Atributos, seria o texto da publicação, acrescentar ou mudar.

**Comment by kenuysaa** [comment]
Pode se tornar um historia do usuario pos morto.
