### ISSUE TITLE
H11. Como amigo do falecido, eu quero poder pesquisar o memorial, para que eu possa encontrar e relembrar momentos importantes compartilhados com ele, acessando fotos, vídeos e textos de homenagens.

### ISSUE THREAD

**Issue by vitoroli22** [kenuysaa/app-homenagens-postumas#16]
# Critérios de Aceitação
- O sistema deve exibir uma barra de pesquisa na página principal do aplicativo.
- O sistema deve permitir que os usuários pesquisem pelo nome do memorial (nome do falecido), além de palavras-chave relacionadas a fotos, vídeos e textos de homenagens.
- Os resultados da pesquisa devem ser exibidos com prioridade para as postagens que mais se alinham às palavras-chave inseridas pelo usuário na barra de pesquisa.
- O usuário deve ter a opção de filtrar os resultados por tipo de conteúdo fotos, vídeos, textos e por data.
- O usuário deve poder selecionar um intervalo de datas para filtrar os resultados da pesquisa, visualizando apenas postagens feitas dentro desse período.
- Se a pesquisa não encontrar resultados, o sistema deve exibir uma mensagem informativa, como "Nenhum resultado encontrado para os critérios de pesquisa especificados."
- A funcionalidade de pesquisa deve suportar múltiplos idiomas.

# Regras de Negócios
- As postagens devem respeitar as configurações de privacidade definidas pelo responsável pelo memorial. Apenas postagens públicas ou compartilhadas com o usuário autenticado serão exibidas nos resultados da pesquisa.
- Postagens arquivadas ou excluídas não devem aparecer nos resultados da pesquisa.

**Comment by vitoroli22** [comment]
Substituir função por "pesquisa" no memorial.

**Comment by kenuysaa** [comment]
Correções de palavras não mensuraveis.
